views:
  - name: cub_3173_demo
    title: CUB-3173 Demo
    cubes:
      - join_path: order_items
        includes:
          - created_at
          - status
          - count
    meta:
      auto_run: false
      default_ui_filters:
        - member: created_at
          operator: is
          value: yesterday
