views:
  - name: orders_transactions
    title: "Orders Transactions"

    cubes:
      - join_path: order_items
        includes: "*"

      - join_path: order_items.products
        prefix: true
        includes: "*"

      - join_path: order_items.orders
        prefix: true
        includes: "*"

      - join_path: order_items.users
        prefix: true
        includes: "*"

      - join_path: order_items.inventory_items.distribution_centers
        prefix: true
        includes: "*"
