views:
  - name: web_events_view
    title: "Web Events"
    description: "Tracks user interactions and behavioral events on the website, including event type, sequence, and associated user profile details."

    meta:
      auto_run: false

    cubes:
      - join_path: events
        includes: "*"

      - join_path: events.users
        prefix: true
        includes: "*"
